### Объединение датафреймов
- merge
### Сводная таблица 
- pivot_table

## Задание
- Скачать данные с Gapminder (https://www.gapminder.org/data)
- Предобработать данные:
  - Развернуть данные
  - Преоброзовать типы
  - Убрать Nan
- Объединить данные через merge
- Вычислить новый столбец использую оба показателя
- Сделать сводную таблицу

In [17]:
import pandas as pd

In [18]:
df_pop = pd.read_csv('../data/raw/gapminder/pop.csv')

In [19]:
df_murder = pd.read_csv('../data/raw/gapminder/murder_total_deaths.csv')

In [20]:
df_pop

,geo,name,1800,1801,1802,1803,1804,1805,1806,1807,...,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100
0,afg,Afghanistan,3280000,3280000,3280000,3280000,3280000,3280000,3280000,3280000,...,124110001.0,124854162.0,125589411.0,126306889.0,126990147.0,127647762.0,128305496.0,128964762.0,129616118.0,130216739.0
1,ago,Angola,1567028,1567028,1567028,1567028,1567028,1567028,1567028,1567028,...,138919849.0,140249378.0,141550054.0,142835147.0,144102524.0,145340832.0,146549586.0,147743369.0,148912810.0,150045574.0
2,alb,Albania,400000,401773,403554,405343,407140,408945,410758,412579,...,1344055.0,1324192.0,1304876.0,1286145.0,1268008.0,1250429.0,1233362.0,1216785.0,1200681.0,1184997.0
3,and,Andorra,2654,2654,2654,2654,2654,2654,2654,2654,...,52781.0,52134.0,51484.0,50843.0,50211.0,49586.0,48973.0,48373.0,47791.0,47222.0
4,are,UAE,40153,40153,40153,40153,40153,40153,40153,40153,...,24075187.0,24298127.0,24521988.0,24747048.0,24973506.0,25201603.0,25431504.0,25663508.0,25897696.0,26134299.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,wsm,Samoa,47300,47292,47284,47276,47268,47260,47252,47244,...,370240.0,371993.0,373663.0,375252.0,376788.0,378279.0,379683.0,381010.0,382317.0,383557.0
191,yem,Yemen,2593000,2593000,2593000,2593000,2593000,2593000,2593000,2593000,...,106510730.0,106998027.0,107459605.0,107895476.0,108308131.0,108699429.0,109068203.0,109414685.0,109738709.0,110035634.0
192,zaf,South Africa,1447911,1453209,1458526,1463862,1469219,1474594,1479989,1485404,...,92399701.0,92635394.0,92860583.0,93085412.0,93300481.0,93502148.0,93695466.0,93893514.0,94101365.0,94314448.0
193,zmb,Zambia,747000,758402,769979,781732,793665,805780,818080,830567,...,61098687.0,61512696.0,61915359.0,62311179.0,62698035.0,63070548.0,63434684.0,63791046.0,64136921.0,64473916.0
194,zwe,Zimbabwe,1085814,1085814,1085814,1085814,1085814,1085814,1085814,1085814,...,36284409.0,36405082.0,36516149.0,36625729.0,36739734.0,36840486.0,36932287.0,37019886.0,37096560.0,37166572.0

In [21]:
df_pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Columns: 303 entries, geo to 2100
dtypes: float64(100), int64(201), object(2)
memory usage: 461.7+ KB

In [22]:
df_pop = pd.melt(
    df_pop,
    id_vars=['geo', 'name'],
    var_name='year',
    value_name='population',
)

In [23]:
df_pop

       geo          name  year   population
0      afg   Afghanistan  1800    3280000.0
1      ago        Angola  1800    1567028.0
2      alb       Albania  1800     400000.0
3      and       Andorra  1800       2654.0
4      are           UAE  1800      40153.0
...    ...           ...   ...          ...
58690  wsm         Samoa  2100     383557.0
58691  yem         Yemen  2100  110035634.0
58692  zaf  South Africa  2100   94314448.0
58693  zmb        Zambia  2100   64473916.0
58694  zwe      Zimbabwe  2100   37166572.0

[58695 rows x 4 columns]

In [24]:
df_pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58695 entries, 0 to 58694
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   geo         58695 non-null  object
 1   name        58695 non-null  object
 2   year        58695 non-null  object
 3   population  58595 non-null  float64
dtypes: float64(1), object(3)
memory usage: 1.8+ MB

In [25]:
df_pop = df_pop.dropna()
df_pop = df_pop.reset_index(drop=True)

In [26]:
df_pop['year'] = pd.to_numeric(df_pop['year'])

In [27]:
df_pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58595 entries, 0 to 58594
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   geo         58595 non-null  object
 1   name        58595 non-null  object
 2   year        58595 non-null  int64
 3   population  58595 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 1.8+ MB

In [28]:
df_murder = pd.melt(
    df_murder,
    id_vars=['geo', 'name'],
    var_name='year',
    value_name='murder_total_deaths',
)

In [29]:
df_murder = df_murder.dropna()
df_murder = df_murder.reset_index(drop=True)

In [30]:
df_murder['year'] = pd.to_numeric(df_murder['year'])

In [31]:
df_murder.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8492 entries, 0 to 8491
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   geo                  8492 non-null   object
 1   name                 8492 non-null   object
 2   year                 8492 non-null   int64
 3   murder_total_deaths  8492 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 265.5+ KB

In [32]:
df_murder

      geo          name  year  murder_total_deaths
0     afg   Afghanistan  1980              1003.27
1     ago        Angola  1980               588.62
2     alb       Albania  1980               206.84
3     and       Andorra  1980                 0.61
4     are           UAE  1980                24.80
...   ...           ...   ...                  ...
8487  wsm         Samoa  2023                 9.62
8488  yem         Yemen  2023               672.60
8489  zaf  South Africa  2023             23066.35
8490  zmb        Zambia  2023              3231.50
8491  zwe      Zimbabwe  2023              2890.83

[8492 rows x 4 columns]

In [36]:
df_merged = pd.merge(
    left=df_pop,
    right=df_murder,
    how='inner', # inner, left, right, outer, cross
    # left_on=['geo', 'name', 'year'],
    # right_on=['geo', 'name', 'year'],
    on=['geo', 'name', 'year'],
)

In [37]:
df_merged

      geo          name  year  population  murder_total_deaths
0     afg   Afghanistan  1980  13169311.0              1003.27
1     ago        Angola  1980   8133872.0               588.62
2     alb       Albania  1980   2735416.0               206.84
3     and       Andorra  1980     35782.0                 0.61
4     are           UAE  1980   1015700.0                24.80
...   ...           ...   ...         ...                  ...
8487  wsm         Samoa  2023    216663.0                 9.62
8488  yem         Yemen  2023  39390799.0               672.60
8489  zaf  South Africa  2023  63212384.0             23066.35
8490  zmb        Zambia  2023  20723965.0              3231.50
8491  zwe      Zimbabwe  2023  16340822.0              2890.83

[8492 rows x 5 columns]

In [38]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8492 entries, 0 to 8491
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   geo                  8492 non-null   object
 1   name                 8492 non-null   object
 2   year                 8492 non-null   int64
 3   population           8492 non-null   float64
 4   murder_total_deaths  8492 non-null   float64
dtypes: float64(2), int64(1), object(2)
memory usage: 331.8+ KB

In [39]:
df_merged[df_merged['geo']=='rus']

      geo    name  year   population  murder_total_deaths
146   rus  Russia  1980  138572623.0             22117.04
339   rus  Russia  1981  139351498.0             22911.95
532   rus  Russia  1982  140247748.0             21654.62
725   rus  Russia  1983  141331278.0             22360.43
918   rus  Russia  1984  142464239.0             23031.18
1111  rus  Russia  1985  143569389.0             23370.65
1304  rus  Russia  1986  144807813.0             20744.57
1497  rus  Russia  1987  146147383.0             19853.78
1690  rus  Russia  1988  147364489.0             21693.38
1883  rus  Russia  1989  148281866.0             24042.34
2076  rus  Russia  1990  148979541.0             27170.30
2269  rus  Russia  1991  149448433.0             30747.27
2462  rus  Russia  1992  148915991.0             41326.54
2655  rus  Russia  1993  148135424.0             55436.43
2848  rus  Russia  1994  148200736.0             63032.08
3041  rus  Russia  1995  148291403.0             61707.64
3234  rus  Russia  1996  148084582.0             52763.59
3427  rus  Russia  1997  147853771.0             48124.68
3620  rus  Russia  1998  147635531.0             47089.87
3813  rus  Russia  1999  147241975.0             52393.54
4006  rus  Russia  2000  146717783.0             55205.97
4199  rus  Russia  2001  146117284.0             56060.85
4392  rus  Russia  2002  145939500.0             57274.39
4585  rus  Russia  2003  145794229.0             55547.19
4778  rus  Russia  2004  145180097.0             52616.03
4971  rus  Russia  2005  144597884.0             49054.78
5164  rus  Russia  2006  144102948.0             40619.60
5357  rus  Russia  2007  143859764.0             36947.00
5550  rus  Russia  2008  143811840.0             34741.11
5743  rus  Russia  2009  143869132.0             31049.51
5936  rus  Russia  2010  143934465.0             29980.64
6129  rus  Russia  2011  144043748.0             28022.56
6322  rus  Russia  2012  144291029.0             26489.65
6515  rus  Russia  2013  144604098.0             25618.76
6708  rus  Russia  2014  144925638.0             24599.62
6901  rus  Russia  2015  145307616.0             23752.39
7094  rus  Russia  2016  145778677.0             21816.40
7287  rus  Russia  2017  146186799.0             19719.29
7480  rus  Russia  2018  146430146.0             18412.39
7673  rus  Russia  2019  146533067.0             17839.32
7866  rus  Russia  2020  146371299.0             17716.63
8059  rus  Russia  2021  145836175.0             16835.88
8252  rus  Russia  2022  145579899.0             16625.00
8445  rus  Russia  2023  145440500.0             16759.91

In [41]:
df_merged['murder_in_100k_pop'] = df_merged['murder_total_deaths'] / df_merged['population'] * 100000

In [43]:
df_merged

,geo,name,year,population,murder_total_deaths,murder_in_100k_pop
0,afg,Afghanistan,1980,13169311.0,1003.27,7.618242
1,ago,Angola,1980,8133872.0,588.62,7.236652
2,alb,Albania,1980,2735416.0,206.84,7.561556
3,and,Andorra,1980,35782.0,0.61,1.704768
4,are,UAE,1980,1015700.0,24.80,2.441666
...,...,...,...,...,...,...
8487,wsm,Samoa,2023,216663.0,9.62,4.440075
8488,yem,Yemen,2023,39390799.0,672.60,1.707505
8489,zaf,South Africa,2023,63212384.0,23066.35,36.490239
8490,zmb,Zambia,2023,20723965.0,3231.50,15.593059
8491,zwe,Zimbabwe,2023,16340822.0,2890.83,17.690848

In [46]:
pd.pivot_table(
    data=df_merged,
    index=['geo', 'name'],
    values=['population', 'murder_in_100k_pop'],
    aggfunc=['mean', 'min', 'max'],
).sort_values(('mean', 'murder_in_100k_pop'))

                              mean                              min  \
                murder_in_100k_pop    population murder_in_100k_pop
geo name
smr San Marino            0.257340  2.795605e+04           0.117336
mco Monaco                0.481767  3.268491e+04           0.333710
vut Vanuatu               0.549143  2.024637e+05           0.510252
qat Qatar                 0.676373  1.197933e+06           0.337017
omn Oman                  0.735941  2.649711e+06           0.527744
...                            ...           ...                ...
hnd Honduras             39.397809  6.962197e+06          28.285788
eri Eritrea              44.514665  2.465625e+06          33.310704
col Colombia             51.537194  3.948529e+07          27.666345
swz Eswatini             55.974133  9.939539e+05          42.212716
slv El Salvador          68.660896  5.737864e+06          50.879063

                                           max
                 population murder_in_100k_pop  population
geo name
smr San Marino      21585.0           0.463285     34769.0
mco Monaco          27122.0           0.589927     38956.0
vut Vanuatu        115660.0           0.596762    320409.0
qat Qatar          275913.0           1.217775   2979082.0
omn Oman          1001248.0           1.490140   5049269.0
...                     ...                ...         ...
hnd Honduras      3727173.0          88.975085  10644851.0
eri Eritrea       1605797.0          57.671476   3470390.0
col Colombia     26104498.0          88.308277  52321152.0
swz Eswatini       596644.0          76.027052   1230506.0
slv El Salvador   4540382.0         131.532765   6309624.0

[193 rows x 6 columns]