In [1]:
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False

In [3]:
import duckdb
import pandas as pd

In [4]:
%load_ext sql
conn = duckdb.connect()
%sql conn --alias duckdb

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [10]:
%%sql
SELECT
    distinct object_name
FROM 
    read_parquet('../data/raw/data_study_area_125_v20250709_csv/data_graduates_study_area_125_v20250709.parquet')
where object_name like '%Саха%'
# LIMIT 
    # 5
;

                object_name
0       Сахалинская область
1  Республика Саха (Якутия)

In [ ]:
# Республика Саха (Якутия)

In [26]:
%%sql
SELECT
    object_name
    , education_level
    , specialty
    , year
    , gender
    , average_salary_fact_avg
    , average_salary_fact_med
FROM 
    read_parquet('../data/raw/data_study_area_125_v20250709_csv/data_graduates_specialty_125_v20250709.parquet')
where 
    object_name = 'Республика Саха (Якутия)'
    and specialty = 'Прикладная информатика'
    and education_level = 'Бакалавриат, специалитет'
order by
    year,
    gender
;

,object_name,education_level,specialty,year,gender,average_salary_fact_avg,average_salary_fact_med
0,Республика Саха (Якутия),"Бакалавриат, специалитет",Прикладная информатика,2016,Всего,114368.226,111791.665
1,Республика Саха (Якутия),"Бакалавриат, специалитет",Прикладная информатика,2016,Женский,93571.746,106083.330
2,Республика Саха (Якутия),"Бакалавриат, специалитет",Прикладная информатика,2016,Мужской,135164.706,125500.000
3,Республика Саха (Якутия),"Бакалавриат, специалитет",Прикладная информатика,2017,Всего,120692.222,105500.000
4,Республика Саха (Якутия),"Бакалавриат, специалитет",Прикладная информатика,2017,Женский,94787.878,99083.330
5,Республика Саха (Якутия),"Бакалавриат, специалитет",Прикладная информатика,2017,Мужской,135263.416,129041.665
6,Республика Саха (Якутия),"Бакалавриат, специалитет",Прикладная информатика,2018,Всего,112970.200,103391.665
7,Республика Саха (Якутия),"Бакалавриат, специалитет",Прикладная информатика,2018,Женский,99098.990,97166.670
8,Республика Саха (Якутия),"Бакалавриат, специалитет",Прикладная информатика,2018,Мужской,118915.004,112750.000
9,Республика Саха (Якутия),"Бакалавриат, специалитет",Прикладная информатика,2019,Всего,105943.888,108250.000
10,Республика Саха (Якутия),"Бакалавриат, специалитет",Прикладная информатика,2019,Женский,NaN,NaN
11,Республика Саха (Якутия),"Бакалавриат, специалитет",Прикладная информатика,2019,Мужской,93681.060,98833.330
12,Республика Саха (Якутия),"Бакалавриат, специалитет",Прикладная информатика,2020,Всего,101978.161,103583.330
13,Республика Саха (Якутия),"Бакалавриат, специалитет",Прикладная информатика,2020,Женский,NaN,NaN
14,Республика Саха (Якутия),"Бакалавриат, специалитет",Прикладная информатика,2020,Мужской,111152.272,113090.910
15,Республика Саха (Якутия),"Бакалавриат, специалитет",Прикладная информатика,2021,Всего,101365.035,90500.000
16,Республика Саха (Якутия),"Бакалавриат, специалитет",Прикладная информатика,2021,Женский,117542.424,78000.000
17,Республика Саха (Якутия),"Бакалавриат, специалитет",Прикладная информатика,2021,Мужской,93950.399,93522.725
18,Республика Саха (Якутия),"Бакалавриат, специалитет",Прикладная информатика,2022,Всего,77560.715,85500.000
19,Республика Саха (Якутия),"Бакалавриат, специалитет",Прикладная информатика,2022,Женский,78075.758,86000.000
20,Республика Саха (Якутия),"Бакалавриат, специалитет",Прикладная информатика,2022,Мужской,NaN,NaN
21,Республика Саха (Якутия),"Бакалавриат, специалитет",Прикладная информатика,2023,Всего,NaN,NaN
22,Республика Саха (Якутия),"Бакалавриат, специалитет",Прикладная информатика,2023,Мужской,NaN,NaN
23,Республика Саха (Якутия),"Бакалавриат, специалитет",Прикладная информатика,2024,Всего,72286.905,77875.000
24,Республика Саха (Якутия),"Бакалавриат, специалитет",Прикладная информатика,2024,Женский,NaN,NaN
25,Республика Саха (Якутия),"Бакалавриат, специалитет",Прикладная информатика,2024,Мужской,72043.750,88725.000